use customer_behaviour;

# Total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as Revenue 
from customer 
group by gender;


# Customers who used discount but still spent more than the average purchase amount?

select customer_id, purchase_amount 
from customer
where discount_applied = "yes" and purchase_amount >= (select avg(purchase_amount) from customer);


# Top 5 products with the highest average review rating?

select item_purchased, round(avg(review_rating),2) as "avg rating"
from customer
group by item_purchased 
order by avg(review_rating) desc
limit 5;


# Average Purchase Amounts between Standard and Express Shipping.

select shipping_type, round(avg(purchase_amount),2)
from customer
where shipping_type in ("Express", "Standard")
group by shipping_type;


# Compare average spend and total revenue between subscribers and non-subscribers to find Do subscribed customers spend more.

select if (subscription_status = "yes", "subscribed", "Not_subscribed" ) as subscription_status,
count(subscription_status) as Total_customers, 
round(avg(purchase_amount),2) as avg_income,
round(sum(purchase_amount),2) as total_revenue
from customer 
group by if (subscription_status = "yes", "subscribed", "Not_subscribed" );


# top 5 products have the highest purchases with discounts applied?

select item_purchased as items,
count(item_purchased) as top_items
from customer
where discount_applied = "yes" 
group by item_purchased 
order by count(item_purchased) desc 
limit 5;


# Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
count(item_purchased) as purchase_count,
round(sum(case when discount_applied = "yes" then 1 else 0 end)/count(*)*100 , 2) as discount_perc
from customer
group by item_purchased
order by discount_perc desc
limit 5;


# To find customers segment is New or Returning or Loyal based on their total number of previous purchases, and to show the count of each segment.

with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


# Top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;


# Customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as repert_customer
from customer 
where previous_purchases > 5
group by subscription_status;


# Revenue contribution of each age group?

select age_group, sum(purchase_amount) as total_revenue 
from customer 
group by age_group
order by total_revenue asc;



select * from customer limit 10;